#!/bin/sh
set -e

SHARE=__SHARE__
ACTION=__ACTION__
SYSROOT=__SYSROOT__
CONFIG=__CONFIG__
CMAKE_BINARY_DIR=$1

PEON=$(node -e "process.stdout.write (require ('path').resolve (__dirname, '$SYSROOT', require (require ('path').resolve (__dirname, '$SYSROOT', '$CONFIG')).bin));")

node "$PEON" "$(pwd)" "$SHARE" $ACTION $CMAKE_BINARY_DIR
