#!/bin/sh
set -e

NAME='<PACMAN.NAME>'
SUBNAME='<PACMAN.SUBNAME>'
VERSION='<PACMAN.VERSION>'
SHARE='<PACMAN.SHARE>'
HOOK='<PACMAN.HOOK>'
ACTION='<PACMAN.ACTION>'
SYSROOT='<PACMAN.SYSROOT>'
DISTRIBUTION='<PACMAN.DISTRIBUTION>'
WPKGACT="$1"

if ! command -v xcraft-peon; then
  [ "$HOOK" = global ] && exit 0
  echo 'xcraft-peon is mandatory but not available in PATH'
  exit 1
fi


[ "$1" = cmake ] && CMAKE_BINARY_DIR="$2" || CMAKE_BINARY_DIR=

_SUBNAME="$(echo $SUBNAME | tr -d '<>')"
if [ -n "$_SUBNAME" ] && [ "$_SUBNAME" != 'PACMAN.SUBNAME' ]; then
  NAME="$NAME-$SUBNAME"
  SHARE="$SHARE-$SUBNAME"
fi

[ -z "$NAME" ] && NAME="$2"
[ -z "$VERSION" ] && VERSION="$3"

_DISTRIBUTION="$(echo $DISTRIBUTION | tr -d '<>')"
[ "$_DISTRIBUTION" = "PACMAN.DISTRIBUTION" ] && DISTRIBUTION="$PEON_DISTRIBUTION"

xcraft-peon "$(pwd)" "$SHARE" "$HOOK" $ACTION "$WPKGACT" "$CMAKE_BINARY_DIR" "$NAME" "$VERSION" "$SYSROOT" "$DISTRIBUTION"
